### ISSUE TITLE
HHRTF - Region default should be selected province only

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#15]
When you compare by jurisdiction and choose a province say Québec, the region should default to Québec only with all the regions left unchecked. The user can select which region they want by checking them.

**Comment by DaxBourcier** [comment]
Similarly, when comparing by specialty, if you click say Ontario, the region should automatically be defaulted to select Ontario. The user can select a different region if they want to.

**Comment by Jrschellenberg** [comment]
To clarify, please see picture attached. In the picture I provided, only "Que." Should be selected, the rest should not.

<img width="961" alt="Screen Shot 2020-03-14 at 3 01 20 PM" src="https://user-images.githubusercontent.com/6064137/76689530-cdfc7c80-6604-11ea-9eb7-7d4faa7ae622.png">

**Comment by DaxBourcier** [comment]
Yes, that's correct, thanks!

**Comment by Jrschellenberg** [comment]
This is now fixed
