### ISSUE TITLE
HHRTF - Comparing jurisdiction title

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#17]
Should be changed to [Selected Specialty] compared by jurisdictions.

**Comment by Jrschellenberg** [comment]
To Clarify Dax's point above, please see my Screenshot attached.

When User Compares by Jurisdictions  and applies filters
Then The Heading should read `[Selected Specialty] compared by jurisdictions.`


<img width="723" alt="Screen Shot 2020-03-14 at 3 05 43 PM" src="https://user-images.githubusercontent.com/6064137/76689707-7ced8800-6606-11ea-8c94-1d4592c168a6.png">

**Comment by DaxBourcier** [comment]
Yes, that's the title that should be changed. Thanks!
