### ISSUE TITLE
Bug- Data Sets are Switching

### ISSUE THREAD

**Issue by amansayal** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#19]
Hi,

If I select ONE jurisdiction (i.e. Ontario or BC ), and select certain indicators like physician #, I will get the correct number (i.e. ~400 for # of ophthalmologists in Ontario,  ~200 ophthalmologists in BC). However, if I compare two jurasdictions, the numbers get swapped. For example, in the stated example, it will show ~200 ophthalmolgists in Ontario and 400 ophthalmologists in BC.

**Comment by ghost** [comment]
I found this to be an issue as well! Looking at Ophthalmology in ON, the average # physicians initially said 17 (which is incorrect) when I was comparing with AB, BC, ON, and NL. Then I tried looking at ON only and 2 things happened: 1) it showed ON, BC, ON again, and NL; and 2) it showed the correct average for the second ON result (449.50) but not the first, which seems to have been swapped with BC.

Screenshots included below.

<img width="1792" alt="Screen Shot 2020-04-17 at 3 49 55 PM" src="https://user-images.githubusercontent.com/63875796/79609177-481c9700-80c4-11ea-8de6-18ca4064254b.png">
<img width="1792" alt="Screen Shot 2020-04-17 at 3 54 11 PM" src="https://user-images.githubusercontent.com/63875796/79609180-48b52d80-80c4-11ea-93ec-325d83e54669.png">

**Comment by ghost** [comment]
Numbers seem to be off for Cardiology # of physicians as well. I think the NL and PEI numbers are swapped ... and NWT should be 0. 

(also side note, the NWT link in the provincial resources doesn't have the same heading as the others) 

Screenshots for both below.

<img width="1792" alt="Screen Shot 2020-04-17 at 4 01 46 PM" src="https://user-images.githubusercontent.com/63875796/79609835-6d5dd500-80c5-11ea-89b4-133104b384f5.png">

**Comment by basumoni** [comment]
This also happens when comparing specialties in one jurisdiction: For example, here I am comparing multiple specialties in Canada - data sets (here I'm using # of physicians, # of vacancies, physician-pop ratio) seems to have been swapped for GIM vs Geriatrics, although critical care is correct.
![swapped_specialties](https://user-images.githubusercontent.com/63878446/79626290-fa705080-80fc-11ea-9b55-a59a9b23911f.jpg)

**Comment by Jrschellenberg** [comment]
Great find everyone! This is definitely a bug that is going on. I'll let you know once it's fixed.

**Comment by mlaniereyes** [comment]
@Jrschellenberg 
swap issue is hopefully working now. If they verify, that would be appreciated. 

regarding the issue where the provinces are deleted but still shown in the table UI, Justin will look into it. Thank you :) 

NOTE:
sorry, the update is still on my branch and not yet merged. Justin will update the client to verify it once it's deployed. Thank you :)

**Comment by Jrschellenberg** [comment]
Please Confirm, this is now fixed and working
