### ISSUE TITLE
PD responses format + link doesn't work 

### ISSUE THREAD

**Issue by ghost** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#20]
Re: PD responses tab

1. For the Ontario PD comments, the questions should be spaced out ... perhaps we should've inputted the responses with a | break between every question?

2. For "To see all Program Director responses for every specialty and for every year click here" - the link over "here" doesn't open on its own. When I right-clicked and selected "Open link in new tab" it took me to the "No results" page. Screenshots included below.

* also in the actual table, it says "PROGRAM DIRECTOR RESPONSE_COMMENT" and "PROVINCIAL RESOURCES" - these may be redundant since the comments are already in the tabs below.

<img width="1791" alt="Screen Shot 2020-04-17 at 2 58 40 PM" src="https://user-images.githubusercontent.com/63875796/79604578-58307880-80bc-11ea-800d-1238449310ed.png"> 

<img width="1792" alt="Screen Shot 2020-04-17 at 3 01 14 PM" src="https://user-images.githubusercontent.com/63875796/79604576-5797e200-80bc-11ea-8931-d978358ddae4.png">

**Comment by st4nya** [comment]
Numbers seem to be off for Cardiology. I think the NL and PEI numbers are swapped ... and I think NWT should be 0. 

(also side note, the NWT link in the provincial resources doesn't have the same heading as the others) 

Screenshots for both below.

<img width="1792" alt="Screen Shot 2020-04-17 at 4 01 46 PM" src="https://user-images.githubusercontent.com/63875796/79609706-3687bf00-80c5-11ea-8fca-84f87e404794.png">

**Comment by Jrschellenberg** [comment]
Thanks you for finding this! I will bring this to Attention with Dax to discuss it in more detail

**Comment by DaxBourcier** [comment]
This here:
https://drive.google.com/drive/folders/117AzAJcCTmHXuuW6PFLLhMIZ62NweP5A?usp=sharing
is the official link for the "To see all Program Director responses for every specialty and for every year click here"

**Comment by Jrschellenberg** [comment]
Perfect, Thanks Dax!

For Mel.

Just need to Add the link above, Don't worry about the original issue, this will still require some coordination between Dax and I

**Comment by mlaniereyes** [comment]
@Jrschellenberg 
The link has been updated/added in my branch.. Client can verify once it's merged. Thank you. :)

**Comment by Jrschellenberg** [comment]
This one Will be worked on After MVP

Currently, Ontario PD responses are formatted differently from other PD Responses

1.) Need to Wipe Database containing current PD responses
2.) Need to Update PD responses to contain a new delimiter
3.) Add Logic to the front end to Allow OPTIONALLY a 3rd delimiter
4.) Add the new PD responses to Database.

**Comment by DaxBourcier** [comment]
I think this is completed right?

**Comment by Jrschellenberg** [comment]
A lot of issues surrounding this ticket have been resolved, however there was still one more thing.
This was revolving around the Ontario PD responses needing another Delimiter. 

If it is possible, I would like to hold off on this feature until after Phase 2 and launch of the AGM. But we can either close this ticket and create a new one for that request or keep this one open for visibility

**Comment by Jrschellenberg** [comment]
Add a new Delimiter, that will do a <br /> on the page. Will inform HHRTF of delimiter to use.

**Comment by Jrschellenberg** [comment]
Hey @DaxBourcier and @st4nya 

So I am going to Suggest, as the third Delimiter we use the following:

`@@`

So in Total we have the following Delimiters now:

`~~`
`||`
`@@` <-- New Addition


Can you Fill out The template, with both the following for me

1.) An example of PD responses, using this new delimiter
2.) An Example of Speciality resource links using this new delimiter

**Comment by Jrschellenberg** [comment]
O Also, one last comment, Currently the Logic for Delimiters is like this. They need to go from outside --> inside


From the Template Documentation

```To fill out the specialty resources and the provincial resources, the field needs to be in the following format:
 
~~ will separate between the name of the link, and the URL (this is to indicate the the text will be hyperlinked with the URL that follows it

|| will separate between links```


To keep it simple for now, perhaps emailing me an example of PD Response, and the Speciality resources, with the Sub Specialities, may work best for now. I may need to investigate and come up with a format for consistency across pre-existing ones!

**Comment by Jrschellenberg** [comment]
@DaxBourcier @st4nya 

The Pd responses are now updated. Please review, and if they are good, we can close this ticket!

**Comment by ghost** [comment]
Hi Justin! @DaxBourcier, Brandon, and I just reviewed the PD responses on the website again. We were wondering if it might be possible for you to go through and format them such that the different responses are separated with a horizontal line to improve readability, remove the bolded text on the non-ON responses, and turn the paragraphs between questions/answers into breaks in the ON responses so that everything looks consistent. We can provide some more detail on how we want the responses to look if needed. The reason we are hoping your team can help out with this is since Brandon and I noticed these bugs arise as we were importing the responses from Excel --> Word --> the doc2html converter, but we didn't know how to correct them because we don't know HTML. Thanks!

**Comment by Jrschellenberg** [comment]
Hey there Misty!

Sorry, but the issue is I don't know how you want it formatted. It also seems like you want them very specifically formatted. This is why I gave you the ability to use HTML, as well as the doc2html converter.

Are either you or Brandon free? We could perhaps schedule a call and discuss this?

**Comment by ghost** [comment]
Hey Justin, 

It was mostly the ON responses that needed significant reformatting (the questions needed to be grouped with the respective answers), but that’s been done already. We mostly want them all to look consistent throughout, with horizontal lines separating each response. The other provinces just need to be unbolded with horizontal lines separating the individual responses. I’ve cc’d Brandon and Dax to this email, maybe we can meet quickly to discuss further! 

Thanks,

Misty

**Comment by Jrschellenberg** [comment]
If you would like them to look consistent throughout. We will have to reenter all of the PD responses again.

If you would like to add Horizontal lines, we can, you will have to insert them through Word.

Perhaps we can meet and I can educate you on how to enter the data in more detail? Sorry, but the CFMS will need to be responsible for their data and understand how to enter it into the DB correctly, or else there will be issues in the future!

**Comment by ghost** [comment]
I spoke with Dax and Brandon and we’ve come up with two potential solutions: 

1. Could we put all of the responses on a Word doc, and your team can convert them into HTML? The problem isn’t really the conversion process itself, it’s that we aren’t able to correct for issues as they arise with the HTML version - i.e. with the breaks/paragraphs, I tried clearing the formatting and re-formatting them the way I wanted, and it was still formatting some of the responses with breaks and others with paragraphs. So it looked fine on Word, but the HTML output was not what we wanted.

2. Can we use the non-ON responses from before, and keep the ON responses as they are now? 

We don’t really feel comfortable redoing all of the PD responses again since it took Brandon and I about 4-5 hours each to do it again last time, on top of the 4-5 hours per person it took for the first entry. Seeing as how there is a high likelihood of the responses having some bugs or errors again, we’re afraid that if we re-did all of them, there would still be some issues with the responses. 

What are your thoughts?

**Comment by Jrschellenberg** [comment]
Hey Misty!

Let me see if we can do something with Option 2. I should be able to differentiate responses between Ont and the rest, and apply the new Format to only Ont, while keeping the old format for the rest.

I will do something of the following:
1.) Reimport all the old PD responses except for all Ontario ones.
2.) Update the logic to split out all Pd responses of the following

- Ontario PD responses

- Rest of Pd responses

I will then apply the new Format to Ontario and apply the old format to the Older PD responses

Let me know if this sounds accurate and works?


We can then circle back and address the PD responses at a later Date, after launch!

**Comment by ghost** [comment]
To clarify, this means that we will see the old format for the non-ON responses (i.e. MUN comment “...”) and the current format for the ON responses? After the AGM, can we update only the ON responses to be formatted more consistently and keep the other responses as they are?

If so, I think that is a good start!

**Comment by Jrschellenberg** [comment]
That is correct

**Comment by Jrschellenberg** [comment]
@st4nya This is now updated on Staging and Production.

I Updated the PD responses, to have all except Ontario be the original Data upload from April.

All Ontario ones are using the new html format.

All non Ontario pd responses, will show the old Format with the delimiter

All Ontario PD responses will show using the new HTML format.

If this is good. You can close this ticket! If you find something, just keep it open and let me know!

**Comment by DaxBourcier** [comment]
I REALLY like how we have the province show up on top of the responses provided. This is extremely useful when we compare more than one province and works really well for the Ontario ones because then the user can see that its just the Ontario responses are slightly different than the rest. I'll let @st4nya and @BrandoCC comment before we close this. Thanks to the team for working on this so hard!!

**Comment by ghost** [comment]
Looks much better! Agree with @DaxBourcier that the province title is super helpful. Thanks for sorting this out!
