### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by ghost** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#21]
I think the bigger numbers (>1,000) would be easier to read with commas. For example, 300000.00 = 300,000.00. I noticed this specifically with the wage and number of physicians. Screenshot included below.

<img width="1792" alt="Screen Shot 2020-04-17 at 3 10 49 PM" src="https://user-images.githubusercontent.com/63875796/79605400-d4778b80-80bd-11ea-9479-28f58af883fc.png">

**Comment by Jrschellenberg** [comment]
This is a nice improvement that we can quickly add I feel. 

Context for myself for later

var n = 34523453.345
n.toLocaleString()
"34,523,453.345

**Comment by Jrschellenberg** [comment]
Remove (1) from Data points, Allow (2), but if there is only 1 Source, Remove the Text from it

**Comment by Jrschellenberg** [comment]
This is now Fixed
