### ISSUE TITLE
Specialty resources do not show up

### ISSUE THREAD

**Issue by basumoni** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#22]
Re: Specialty resources tab

for any given specialty, whether comparing specialties or jurisdictions, specialty resources tab at the bottom is always empty, example here:
![Annotation 2020-04-17 223231](https://user-images.githubusercontent.com/63878446/79626086-6c479a80-80fb-11ea-8bdd-70abb4e4c5fd.jpg)

**Comment by Jrschellenberg** [comment]
Good find! I will investigate this, I believe there was issues with the CSV and I may have forgotten to reimport this data! Thank you for bringing this to my attention!

**Comment by Jrschellenberg** [comment]
This is now Fixed
