### ISSUE TITLE
Missing data issue

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#23]
![Screen Shot 2020-04-19 at 8 37 12 PM](https://user-images.githubusercontent.com/62123024/79702772-9923bb00-827d-11ea-9c60-5a45085a374d.png)

**Comment by Jrschellenberg** [comment]
May be related to #19

**Comment by Jrschellenberg** [comment]
Dax, May you clarify as to what the Bug is? I took a look at the data and it appears this is rendering correctly, To clarify there is NO Data that is missing.

Are you referring perhaps to the Program Director Comments missing?

Please let me know!

**Comment by Jrschellenberg** [comment]
This is now Fixed and complete!
