### ISSUE TITLE
Duplications in select specialty menu

### ISSUE THREAD

**Issue by basumoni** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#24]
There are two duplications in the list of specialties on the select specialty menu (on the sidebar). These duplications are:
Otolargyngology-Head and Neck Surgery
Public Health and Preventive Medicine

In both of these cases, if you select the first option, the tables return empty. The second one returns data and seems to be functional. Attached a picture here to see:
![ent_redundancy](https://user-images.githubusercontent.com/63878446/79912297-cf814780-83ef-11ea-9e48-48778d0edba0.jpg)

**Comment by Jrschellenberg** [comment]
This should be Easy to fix, just need to remove it from the Database on the Backend. This is due to Old Data persisting when we were creating the template.


for Dev:

Need to remove `Otolargyngology-Head & Neck Surgery`
Need to remove `Public Health & Preventive Medicine`

**Comment by Jrschellenberg** [comment]
This is now Fixed and Live
