### ISSUE TITLE
Switch Main Resources

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#25]
The links to CaRMS, CIHI, CMA and CAPER should be under the Data source tab rather than the other resources tab. (see pictures 1 and 2).
![Screen Shot 2020-04-25 at 7 58 32 PM](https://user-images.githubusercontent.com/62123024/80292798-a504f680-872f-11ea-9302-258d26acad14.png)
![Screen Shot 2020-04-25 at 7 58 38 PM](https://user-images.githubusercontent.com/62123024/80292800-a6362380-872f-11ea-9b28-5ba4e5e933a0.png)

Also

If possible to have the following order for the tabs (from left to right): PD responses, specialty, provincial,  other resources and data source.

**Comment by Jrschellenberg** [comment]
Dax, are you ok if we just Merge these two Tabs together?

We could have the following:

For now would just be hardcoded, but we could add the new Sources and link them.

Would have the message `For GDPR Compliance...`
Then below it would have the content from `Other resources and Information`

**Comment by Jrschellenberg** [comment]
For Task

1.) Remove Tabs Data Sources, and, Other Information
2.) Create Tab called "Data Sources and Other Information"
3.) Combine the Information from 1 above into tab in 2 above.

4.) Reorder them to the following:
 (from left to right): PD responses, specialty, provincial, Data Sources and Other Information

**Comment by Jrschellenberg** [comment]
This is now merged and live
