### ISSUE TITLE
Learn More --> User Guide

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#27]
Just change the wording from "Learn More" to "User Guide"

![Screen Shot 2020-04-25 at 8 19 06 PM](https://user-images.githubusercontent.com/62123024/80293011-0b8b1400-8732-11ea-8fad-1a23e3e8041d.png)

**Comment by mlaniereyes** [comment]
@Jrschellenberg 
changes in my branch.. Client can verify once it's merged.
