### ISSUE TITLE
Changes in wording (under this issue tracker)

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#28]
This sentence should read "There are no specialty resources for this specialty."

![Screen Shot 2020-04-25 at 8 40 18 PM](https://user-images.githubusercontent.com/62123024/80293358-11cebf80-8735-11ea-87eb-63c43b217ca4.png)

**Comment by DaxBourcier** [comment]
Similarly, this sentence should read "There are no provincial resources for this province"

![Screen Shot 2020-04-25 at 8 43 49 PM](https://user-images.githubusercontent.com/62123024/80293413-830e7280-8735-11ea-8221-d67b3bba989c.png)

**Comment by DaxBourcier** [comment]
Should read "Other Useful Resources:"
![Screen Shot 2020-04-25 at 8 48 41 PM](https://user-images.githubusercontent.com/62123024/80293497-40996580-8736-11ea-90ae-6c86422a11ab.png)

**Comment by DaxBourcier** [comment]
These should not have : after the name.
![Screen Shot 2020-04-25 at 8 49 50 PM](https://user-images.githubusercontent.com/62123024/80293507-5870e980-8736-11ea-811c-fe5aa39da864.png)

**Comment by DaxBourcier** [comment]
This sentence would be better as normal text (to match the same size and font as the text under the provincial resource and specialty resources tabs). It should read "This work is in compliance with the General Data Protection Regulation. The (#) after data points means that the number shown was averaged by that number of the following sources."

![Screen Shot 2020-04-25 at 8 51 51 PM](https://user-images.githubusercontent.com/62123024/80293535-9a019480-8736-11ea-8970-861899ec7705.png)

**Comment by DaxBourcier** [comment]
When you look at Program Director responses, it seems to always start with a dash "-" rather than the text itself. If we could just remove that dash and have the text start from the top that would be great.
![Screen Shot 2020-04-25 at 9 11 44 PM](https://user-images.githubusercontent.com/62123024/80293836-91f72400-8739-11ea-806e-8994d5ce124a.png)

**Comment by mlaniereyes** [comment]
@Jrschellenberg 
changes in my branch.. Client can verify once it's merged. Thank you. :)

**Comment by Jrschellenberg** [comment]
These are confirmed and live, Thanks Mel!
