### ISSUE TITLE
Table view "running out of space"

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#29]
If you add a lot of columns in a table it runs off at the very right as seen in the screenshot.
![Screen Shot 2020-04-25 at 9 25 41 PM](https://user-images.githubusercontent.com/62123024/80294019-78ef7280-873b-11ea-98bf-5d50c1ebbda5.png)

**Comment by Jrschellenberg** [comment]
Dax, We will need to talk about this. This is something that we brought forward to you originally when we designed the Application.


This is a Feature, not a bug as there is no easy way to display massive amounts of data unless we use a scrollable Table!
