### ISSUE TITLE
Map View initial view

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#30]
I was wondering if it would be possible to se the map to appear in this position on the screen as well as with the text boxes in this set up exactly, so that no matter how many data sets a user runs at a time, that they will fully be visible right off the bat without them having the move anything around.
![Screen Shot 2020-04-25 at 9 40 01 PM](https://user-images.githubusercontent.com/62123024/80294209-53636880-873d-11ea-9951-834c6054ccda.png)

**Comment by Jrschellenberg** [comment]
This is achievable, but due to time constraints, if we can offset this until after MVP. As this will require updating the GeoJSON, and finding all of the lat, lng coordinates individually, I also will have to setup the State to be dynamic through the geoJSON as well.

But this is totally doable!

**Comment by Jrschellenberg** [comment]
This is now merged and live on Latest Staging Build

https://quirky-edison-afaa90.netlify.com/
