### ISSUE TITLE
Program Director Responses Alignment 

### ISSUE THREAD

**Issue by BrandoCC** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#31]
When selecting a specialty the comments sometimes get split into two different sections and put on the other side of the column. For example, comparing by specialties and selecting NL All regions, if you select Anesthesiology when you open the program director responses the comment is split into two different columns. This makes it seem like there are two separate comments when in fact there is only one. There are multiple cases where this occurs when I search specialties.

**Comment by DaxBourcier** [comment]
How about we have have one column for the PD responses while keeping the other tabs as two columns? I think that would solve the issue.

**Comment by Jrschellenberg** [comment]
This is now Fixed!
