### ISSUE TITLE
Map View: Selecting a province

### ISSUE THREAD

**Issue by BrandoCC** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#33]
Whenever I click on a province it becomes highlighted. However, I cannot select another province afterwards, it only keeps the initial province highlighted.

**Comment by Jrschellenberg** [comment]
May you check if you are comparing provinces or Specialties?

If you are comparing specialties, then this a Feature and not a bug.

By design, the Application only allows for 1 Health region to be specified at a time if you are comparing by specialties!

**Comment by Jrschellenberg** [comment]
After talking with Dax, we believe this is in regards to the Highlighting Yellow of the Map. 

My apologies, I misunderstood what you said before. This is a feature that we will be implementing after the MVP

Feature,

1.) User is on map view
2.) User hovers mouse over Province geoJSON
3.) GeoJSON highlights
4.) User Clicks Highlighted province
5.) Map Zooms into Regional Map view of Province

**Comment by Jrschellenberg** [comment]
This is now Impelemented and will be added on next release
