### ISSUE TITLE
On tablet view, problem with scrolling to the very bottom 

### ISSUE THREAD

**Issue by a-ht-d** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#34]
![6D69C1F3-750C-4C1E-BA56-09973E557500](https://user-images.githubusercontent.com/64338618/80294872-7f7dea00-873b-11ea-9996-61784a006656.jpeg)

When I inputted all the data sets, the last two rows are difficult to scroll to - it bounced back up when I tried to scroll down and on a tablet, the scroll had to be held down to view it.

**Comment by Jrschellenberg** [comment]
Mel, 

Can we `add some padding for the Main content` so that the tables show up without needing to scroll the Slider Table underneath/

As well, can we `Decrease the height` of the `slider table`

**Comment by mlaniereyes** [comment]
@Jrschellenberg 
changes in my branch.. Client can verify once it's merged. Thank you. :)

**Comment by Jrschellenberg** [comment]
Look good Mel! closing for now
