### ISSUE TITLE
“Provincial Resources” link overlap (tablet view) 

### ISSUE THREAD

**Issue by a-ht-d** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#35]
![A368F5E1-4381-476D-9677-BFD1E3DB40DA](https://user-images.githubusercontent.com/64338618/80295053-51010e80-873d-11ea-9d45-75739f02221e.png)

Formatting issue that might need fixing

**Comment by Jrschellenberg** [comment]
Just needs some Css Fixing.

**Comment by mlaniereyes** [comment]
@Jrschellenberg 
changes in my branch.. Client can verify once it's merged. Thank you. :)

**Comment by Jrschellenberg** [comment]
Fix confirmed, Thanks Mel!
