### ISSUE TITLE
Program director comment + provincial resources + specialty resources appearing as data set

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#38]
![image](https://user-images.githubusercontent.com/62123024/86093060-c31b0a00-ba84-11ea-828e-08f4fe537990.png)

**Comment by Jrschellenberg** [comment]
Hey @DaxBourcier 

This is highly likely due to me using a bad template by accident when I uploaded the Test Data. This issue will resolve itself when we Re import the Data again before launch!

**Comment by Jrschellenberg** [comment]
Leaving Open for reference

**Comment by Jrschellenberg** [comment]
This is now resolved!
