### ISSUE TITLE
Graph title and axes

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#39]
1) The graph title would have to be changed to reflect whether the user selects a province, a health region or Canada as a whole
2) Center title with the middle of the graph
3) Please remove the "data set:" before the data set name in the y axis.
4) Make enable disable min/max the same font and size as the graph 

![image](https://user-images.githubusercontent.com/62123024/86093439-57856c80-ba85-11ea-927c-ca4082a0b777.png)

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is now fixed

Please review and if there are any issues we can reopen the Ticket!
