### ISSUE TITLE
HHRTF - "Unknown" region causing Data Rendering Issues

### ISSUE THREAD

**Issue by Jrschellenberg** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#4]
Currently, Regions is the only unique value to look up Jurisdictions, However, there are multiple 
Jurisidctions with the Region of Unknown.

Therefore, cannot properly display information from regions of "Unknown" Until we resolve the relationship between Jurisdiction and Region

**Comment by mlaniereyes** [comment]
Note to backend:
Regions are not unique. Some provinces have similar 'Unknown' value. would it help if I'm sending a province request using the province ID instead and getting response with the same ID too like we're supposed to do with datasets?

**Comment by Jrschellenberg** [comment]
Confirmed this John, This will not be an issue since The Unknown is being Stored as an id on the backend
