### ISSUE TITLE
Some issues with data displayed

### ISSUE THREAD

**Issue by basumoni** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#40]
Some of the data displayed for different data sets cannot be true
I have taken some screenshots here, but for example: in one graph view, the average wage for obstetrics in 2017 is 1084, but in 2019, it's 417996. Unrealistic numbers also appear for median age (ex median age for Obstetrics in 2017 is like 1750)

![Annotation 2020-06-30 202408](https://user-images.githubusercontent.com/63878446/86189974-163a9e80-bb11-11ea-8b22-43118406e21c.jpg)
![Annotation 2020-06-30 202518](https://user-images.githubusercontent.com/63878446/86189982-19ce2580-bb11-11ea-9c55-8f7d28d6cd46.jpg)

**Comment by Jrschellenberg** [comment]
@basumoni Any Data from before the year 2019 is Test Data, I ran it through a Number Generator. It is merely for Development purposes only. Sorry!

Once we get the previous data and can add it in. It will then reflect real data.
