### ISSUE TITLE
Left toolbar steps

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#41]
If possible to have the Table view/graph view/map view as Step 1 using the same format as the current step two where the user selects between the three options. The current step 1 would become step 2 and so on.
![image](https://user-images.githubusercontent.com/62123024/86672453-0c131700-bfcd-11ea-9cdb-cf8af4377fe1.png)

**Comment by Jrschellenberg** [comment]
This is now fixed and cycled into next release
