### ISSUE TITLE
Zoom in and out button on map view

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#42]
Is there a way to move the zoom in and out button so that it is not get covered by the bottom toolbar? (could move up under the fullscreen option if possible.

![image](https://user-images.githubusercontent.com/62123024/89845955-489adb00-db56-11ea-9e8c-517b63093e6b.png)

**Comment by cfms-website** [comment]
This is fixed
