### ISSUE TITLE
Specialty resources duplicates in map view

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#43]
Works fine in Table and Graph view but is duplicated maybe 50x or so in map view for every specialty. Example here for general surgery

![image](https://user-images.githubusercontent.com/62123024/89846035-81d34b00-db56-11ea-941e-cb14a8a41d1f.png)

**Comment by Jrschellenberg** [comment]
Although it appears like they are similar, those pieces of text are not, and that is why they are appearing twice.

here is an example of a couple

![Screenshot from 2020-08-17 18-24-57](https://user-images.githubusercontent.com/6064137/90453749-1558ce80-e0b7-11ea-801d-c7ee0d321228.png)


Notice the `4` and `5` highlighted in the picture.


The solution for this would be to Go through and fix the Excel sheet, ensuring that the Data Strings are identical, that way as we currently are, we can remove duplicates and only present the user with a unique Dataset.

It may be worthwhile to wait for this fix when we update the Backend for storing provincial, and specialty resources, as this is one of the many technical debts that is occurring from the current structure!

Let me know your thoughts Dax!

**Comment by DaxBourcier** [comment]
Yes sure! We will make sure the text is unique in the upcoming specialty and provincial resources templates. I wonder if this happened because the text was dragged across cells and Excel automatically added a number at the end (sort of like it does for strings of numbers). Either way I'm glad we found this because that means many of those links likely don't work. Thanks!

**Comment by Jrschellenberg** [comment]
No problem! Let me know once you have rectified the Specialities resource information in the Template, and then I will be able to do a fresh upload of it!

**Comment by cfms-website** [comment]
This is now Fixed with the upload of new Specialties resources format!
