### ISSUE TITLE
Provincial resources not showing up in table and graph view

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#44]
Provincial resources not showing up at all in table and graph view:

![image](https://user-images.githubusercontent.com/62123024/89846259-19d13480-db57-11ea-9dad-a7345880b545.png)

**Comment by Jrschellenberg** [comment]
This is working as intended, there are no Provincial resources available for the Region of Canada - All

**Comment by DaxBourcier** [comment]
Hahaha that's what is was. I guess I was just used to selecting Canada-All for graph view because it has the dummy data. Sorry about that.
