### ISSUE TITLE
Not all provincial resources listed

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#45]
Not all provincial resources listed (in map view because that's the only one working as of now):

![image](https://user-images.githubusercontent.com/62123024/89846376-6f0d4600-db57-11ea-8cec-bd3692c9990c.png)

Missing all provinces East of Saskatchewan.

**Comment by Jrschellenberg** [comment]
Good find! I believe this is my fault, I had canceled an upload early when I was creating the uploading functionality and thought I had imported the provinces correctly!

I reran the upload and they are now all there!
