### ISSUE TITLE
Remove text in Other Resources

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#46]
Remove the text "This work is in compliance with the General Data Protection Regulation. The (#) after data points means that the number shown was averaged by that number of the following sources."

Keep "Here are the links to the main data sources supporting this platform" at the top left AND add a ":" 

At the bottom of this page, please add "For more information on how to interpret the data or methodology, please visit the user guide" (if possible to link the user guide there as well).

![image](https://user-images.githubusercontent.com/62123024/89846492-c8757500-db57-11ea-9ac3-397e1943d754.png)

**Comment by Jrschellenberg** [comment]
@DaxBourcier I have updated it, and can be seen on the newest version of Staging that will be released.

May you provide me with the link that you want for the user guide to point to? I will update it in this section here, as well as in the Pop up modal User guide for users!

**Comment by DaxBourcier** [comment]
Will have this soon.

**Comment by DaxBourcier** [comment]
Hey Justin,

Here is the PDF for the User Guide:
https://drive.google.com/file/d/13IfnTgLb8Jqy9832m2sRXGtugmQUvYet/view?usp=sharing

It's in the same folder as the Master PD Comment document. However, I was wondering if it was possible to include just have it open directly as a pdf hyperlink? (instead of having to download te PDF from the Google Drive?)

Thanks a lot!

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is now added in the User guide Modal. Please review it and if it is good, we can close this ticket!

**Comment by DaxBourcier** [comment]
Great!
