### ISSUE TITLE
PD comments are not working in any views for all specialties

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#47]
This is an image of a table comparing all specialties with all data sets.

![image](https://user-images.githubusercontent.com/62123024/89846796-9e708280-db58-11ea-94cb-cdccb02e14da.png)

**Comment by Jrschellenberg** [comment]
Can I have an example of what you queried please! I need a screenshot of the whole screen, mainly the sidebar showing what Data you queried to get this result!

**Comment by Jrschellenberg** [comment]
O my apologies, I see you queried for all specialties and datasets. What Region did you query for Dax!

**Comment by DaxBourcier** [comment]
Hey Justin,

Replying here because I'm on my phone. I'm pretty sure this specific example was for Canada, but it doesn't not work for any jurisdiction. Are they appearing anywhere when you run a query?

Thank you,

Dax Bourcier

On Aug. 11, 2020 11:36, Justin Schellenberg <notifications@github.com> wrote:

O my apologies, I see you queried for all specialties and datasets. What Region did you query for Dax!

**Comment by Jrschellenberg** [comment]
I have started investigating this. I am using a CSV that we previously uploaded, it isn't adding the PD responses into the Database, will let you know once I have a more informative update as to what the issue is!

**Comment by Jrschellenberg** [comment]
@DaxBourcier This should now be fixed. The template I had for PD responses, didn't have any source assigned to it. So I as we previously discussed, assigned it the source of `CIHI`

This is now working. For Canada, there are no PD responses in the template that I currently have 

If there is now, we will need the HHRTF fill out an updated PD responses Dataset. Once they have, I can upload it to add to the Database!

If there are no more issues, you can close this ticket. If you find some, just let me know!

**Comment by DaxBourcier** [comment]
Looks good! Thanks
