### ISSUE TITLE
Apply button half hidden on intitial view

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#48]
This is really a tiny detail, and is purely design, but would it be possible to move the apply button upwards so that the user can see the whole button of the initial view?

![image](https://user-images.githubusercontent.com/62123024/89846896-d5df2f00-db58-11ea-83ff-9f6078ba49b6.png)

**Comment by cfms-website** [comment]
This is fixed, and will show up in the next release of Staging
