### ISSUE TITLE
Graph view - years

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#50]
Please remove years 2014 and before for the year selection everywhere on the platform. We only have data from 2015 onwards are are not planning on going back any earlier.

![image](https://user-images.githubusercontent.com/62123024/90340297-8754e900-dfcd-11ea-834f-be850adbfe50.png)

**Comment by cfms-website** [comment]
These years are only present due to Testing Data for the Graph view. They will be removed when we use Production Data

**Comment by Jrschellenberg** [comment]
Sorry Dax, this was me commenting above, I was still logged into the CFMS account!

I will keep this ticket open just as a reminder and a check for us when we move to production Data!

**Comment by Jrschellenberg** [comment]
I removed all Data from before the year of 2015, closing this for now. However, please note, there is still some test data surrounding "Canada - All" within the Staging Database!
