### ISSUE TITLE
Specialty Demand Layer 

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#53]
1) Could we change No data to "Data Not Yet Available"

2) Could we change all the health region shade colour to yellow ("Data Not Yet Available"). 

2) Further, only some health regions appear at different zoom levels:
![image](https://user-images.githubusercontent.com/62123024/90987027-0f9f3500-e55e-11ea-9623-f738447e03fe.png)
![image](https://user-images.githubusercontent.com/62123024/90987033-20e84180-e55e-11ea-9ec7-f5381323564d.png)
![image](https://user-images.githubusercontent.com/62123024/90987043-35c4d500-e55e-11ea-8ed4-6db03456a338.png)

**Comment by Jrschellenberg** [comment]
Hey @DaxBourcier I updated the Text. 

I unfortunately am having a hard time to reproduce this issue, I queried the exact same parameters and this is what it looks like for me.

![Screenshot from 2020-08-25 21-43-00](https://user-images.githubusercontent.com/6064137/91249299-3905bf80-e71c-11ea-9b50-8d920f9b7779.png)
![Screenshot from 2020-08-25 21-43-34](https://user-images.githubusercontent.com/6064137/91249307-3c994680-e71c-11ea-86e7-3c90c1315d7a.png)


If you are able to reproduce this, can you show me the steps you took to do so! It might be a bug being caused on an edge case that I am missing.

**Comment by DaxBourcier** [comment]
Seems to work fine for me now as well.
