### ISSUE TITLE
Neurology in Graph view - No data

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#54]
There seems to be no data for Neurology in graph view, but the data is available in Table view

![image](https://user-images.githubusercontent.com/62123024/90987311-5a21b100-e560-11ea-8951-23a052c5dc26.png)

**Comment by Jrschellenberg** [comment]
Please Check this, should be fixed now! Along with other Graph Related issues!
