### ISSUE TITLE
Update Map View with CaRMS Regional view

### ISSUE THREAD

**Issue by Jrschellenberg** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#55]
“could we make it so that we have a rule in there for coding that will show the highest view (like most zoomed out view) that actually has data when the user clicks apply. For example say a user selects number of vacancies as their only data set, the initial view would show the provincial level. If the user selects # who ranked first the initial view would be of the Canadian regions.”

@DaxBourcier

**Comment by Jrschellenberg** [comment]
Hey Dax!

Just some questions regarding this issue

1.)Would there be more Datasets?

2.) I can add something that logic in, currently however, if we do it using zoom level. The end-user would have to be zoomed out in order to see the regional mapping.


So for example, if I queried 
`Number of CMG applicants who ranked specialty as first choice`

And was at a zoom level of 4, 5 I would still see the provinces, as they need to still show up on the map view

![Screenshot from 2020-08-24 18-37-08](https://user-images.githubusercontent.com/6064137/91106726-fcad6300-e638-11ea-8bd7-e5bb24910f08.png)



Let me know what you think!

**Comment by DaxBourcier** [comment]
Hey Justin,

There's going to be other issues related to zoom coming up post meeting. There's a few issues with different aspects of the zoom function. It would be easier to organise a 15min call to go over them because it's harder to write out as issues than to talk about while showing you. My next availability would be Friday anytime except 2-5pm ADT. Thanks!

**Comment by Jrschellenberg** [comment]
Hey Dax! I set up a meeting for us on 5:15 PM ADT Aug 28th this Friday!

**Comment by Jrschellenberg** [comment]
Closing as this will be fixed and implemented in Ticket #58
