### ISSUE TITLE
Map view feedback from HHRTF

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#60]
1) In the specialty demand (all colours) and population density layer (some of the darker colours) are fully opaque and you can't see anything below them. If possible to change the colour shade or make them more translucent so we can localize cities and the map below please.

2) Bold the data more and if one of the font colours (light blue) can be changed to something more readable.
![image](https://user-images.githubusercontent.com/62123024/91609702-40141400-e94e-11ea-886f-701eaa5bdba0.png)

3) PD responses still showing up as big chunk of text.

4) If possible to have the pin drop be in the middle of the health region instead of at their extremities. Mostly for health regions.

**Comment by Jrschellenberg** [comment]
1.) I have lowered the opacities. If you need them any lower let me know! We may have to play with the numbers a bit to find something that works!

2.) I have updated all of the Colors to be at least a 4.5, which meets WCAG AA: accessibility standards for normal Text, as well as made it Bold

3.) This will be addressed in ticket 

4.) As we discussed, we will investigate other options for this. 

Dax, please take a look at the latest staging, if 1 and 2 above are to your liking, you can close the ticket. If there's still issues, just let me know!

**Comment by DaxBourcier** [comment]
Hey Justin,

Looks so much better! The only thing would be to make the name of the health region and the numbers below it be in the same font and text size if possible.
![image](https://user-images.githubusercontent.com/62123024/91672185-413a7200-eb03-11ea-815b-e9459f899a70.png)
![image](https://user-images.githubusercontent.com/62123024/91672193-50b9bb00-eb03-11ea-9b2f-b7586c129ef3.png)

**Comment by Jrschellenberg** [comment]
@DaxBourcier I have updated and made the Text a bit large, as well as restructured the tooltip box to accommodate the larger font size. Please review and if it is good, we can close this ticket!

**Comment by DaxBourcier** [comment]
Hey Justin, I'll get feedback from HHRTF tonight on this. Now we loose some space because the text won't fit besides the X, and so the map becomes more cluttered. I wonder if we just made the font smaller (of both the title and numbers below) so that it fits besides the X. Or if we can sneak the X at the bottom right of the box at the same level as the bottom number (but without moving it). Anyways, I'll provide HHRTf feedback tonight for this.

**Comment by Jrschellenberg** [comment]
Hey Dax, that is correct. This is why I originally designed the map that way, to try to accommodate because of the tight spacing. 

It will be a trade-off, You cannot have the very visible text and small space so it will be a compromise that the HHRTF will have to decide.

Once you do, just let me know and I'll see what I can do!

**Comment by DaxBourcier** [comment]
We agreed that it looks perfect as it is!
