### ISSUE TITLE
Initial Map view

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#61]
The initial map view. may be problematic because it looks like we're excluding the territories:

![image](https://user-images.githubusercontent.com/62123024/91610827-5cb14b80-e950-11ea-8be1-9a5a1852c10a.png)

Would it be possible to have the initial view be the Canadian provinces & territories instead of the Canadian regions? Moreover, would it be possible to only few the Canadian regions if there is data that fits in these is queried?

**Comment by Jrschellenberg** [comment]
Similar to #58 Need to reduce Initial zoom constant by 1

**Comment by Jrschellenberg** [comment]
Closing Ticket due to Relation of #58
