### ISSUE TITLE
Zoom level for initial view

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#65]
Hey Justin,

Could we make this zoom level the initial view when you apply a query please:
![image](https://user-images.githubusercontent.com/62123024/92339364-0cdb2e80-f08c-11ea-9153-ae77313ede7c.png)

Thanks!

**Comment by Jrschellenberg** [comment]
Hey there Dax! So to clarify, you want to Zoom the map out I am assuming to show CaRMS data if applicable when the user queries, correct?

**Comment by DaxBourcier** [comment]
Hey Justin,

If possible to show the zoom level in the previous comment when you initially see the map. Right now it's like this and a bit too zoomed in:
![image](https://user-images.githubusercontent.com/62123024/92341835-50866600-f095-11ea-8ced-207ad16b27c1.png)

**Comment by DaxBourcier** [comment]
And yes actually, when you query provincial data, to show the provincial data but at this zoom level (the one in the first comment) so that you can see all of Canada. Otherwise is starts out a bit too zoomed in as shown here:
![image](https://user-images.githubusercontent.com/62123024/92341930-ac50ef00-f095-11ea-916f-e96c7785cde3.png)

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is now updated and can be seen on

https://hhrtf-staging.cfms.org/map#
