### ISSUE TITLE
Only show 2015-2019 years

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#66]
Please only show 2015-2019 data because we won't have any data except CaRMS under 2020 and this may confuse people for release.

![image](https://user-images.githubusercontent.com/62123024/92339695-d4d4eb00-f08d-11ea-9b3a-550c281e90d2.png)

**Comment by Jrschellenberg** [comment]
Yep! this will be only showing 2015-2019 for production. The data on there right now is for testing purposes in the staging environment!
