### ISSUE TITLE
Hospitals appear in wrong place when zoomed out

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#68]
There's a bug where hospitals appear in the wrong place unless zoomed in maximum. Not sure if we can fix this since we outsource it.

![image](https://user-images.githubusercontent.com/62123024/92415605-18803100-f130-11ea-9db2-9cbc90fc52e4.png)

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is now fixed and available to see on staging.
