### ISSUE TITLE
Specialty Demand Layer

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#69]
Hey Justin,

It looks like when you zoom in the specialty demand layer, both the layer of the provincial level and the health region superpose:

![image](https://user-images.githubusercontent.com/62123024/92415845-297d7200-f131-11ea-9fa2-90c6b683a93b.png)

Also, is it possible to have this layer appear as no data available (yellow) for launch since we don't have this data. Thanks a lot!

**Comment by Jrschellenberg** [comment]
Hey there @DaxBourcier Can you clarify what you mean by 

> Also, is it possible to have this layer appear as no data available (yellow) for launch since we don't have this data. Thanks a lot!

To my knowledge, it should be currently doing this. If no data is present, it appears as yellow.

**Comment by Jrschellenberg** [comment]
@DaxBourcier This should now be fixed and can be seen on:

https://hhrtf-staging.cfms.org/map#

**Comment by DaxBourcier** [comment]
Hey Justin

So for the actual layer to show yellow. Like currently as seen below its all different shades of blue:

![image](https://user-images.githubusercontent.com/62123024/93030646-fdfbfb00-f5fa-11ea-9b1a-8fcb70a2647c.png)

We currently dont have any data for specialty demand. so all the shades over every province and health region should be yellow.

Thanks!

**Comment by Jrschellenberg** [comment]
Hey there Dax! I am confused. I thought we were going to use the doctor per 100,000 as a value to calculate the specialty demand?

**Comment by Jrschellenberg** [comment]
@DaxBourcier Please let me know as soon as you can please! So I can make any changes if necessary

**Comment by DaxBourcier** [comment]
Hey Justin, 

yeah we definitely had a misunderstanding for this one. Really easy fix though!

Initially we wanted to set it up for the specialty demand to be "ready" for when we would have this data. In the meantime, we chose to use the same type of "heat map" layer idea to do the physician to 100,000. This being said, the layer that contains this data should be called "Physician Density". So maybe just change "Specialty Demand" to "Physician Density". 

If it is not too much work, ideally we would have another layer that would say "Specialty Demand" that would show everything as yellow because we don't have data for this yet.

Also just to make sure, did you use the thresholds that Owen had proposed for the physician to 100,000? I remember we had a discussion about having to reformat some of the cells to add a new column and show a number representing the percentile, but wasn't sure where we ended up on that one. 

Thanks a lot!

**Comment by Jrschellenberg** [comment]
@DaxBourcier I added a Map layer for Specialty Demand that has no Data.

Please note, it functions similarly to the new Physician Demand, IE you have to query first before you can see the Map Layer.

I also gave this one a lower opacity compared to the Physician demand layer since there is no data for now.

**Comment by DaxBourcier** [comment]
Hey Justin, the title should say "Physician Density" not physician demand. Just a little switch, otherwise looks super!!

**Comment by DaxBourcier** [comment]
Also, the Specialty Demand legend appears when you initially apply data (even before selecting the layer).

**Comment by DaxBourcier** [comment]
![image](https://user-images.githubusercontent.com/62123024/93208293-c001f280-f732-11ea-9899-5295cb3c77b7.png)

**Comment by DaxBourcier** [comment]
Also, the specialty demand layer is automatically selected when you apply any query. Please make it so that it is unselected at first. Thanks

![image](https://user-images.githubusercontent.com/62123024/93208445-f63f7200-f732-11ea-810d-4036726d8e23.png)

**Comment by Jrschellenberg** [comment]
Hey @DaxBourcier can you confirm if you are querying with the Layer applied already?

If this is the case, this is working as expected.

I just tried and the Layer does not apply unless the user has it specifically applied from the Dropdown in the top right of the Map view!

If you want I can remove it every time they apply filters, however, I feel this would go against some design principles

**Comment by DaxBourcier** [comment]
Ah! that must have been it, my bad! 

Just need to change the wording to "Physician Density" now for the layer:

![image](https://user-images.githubusercontent.com/62123024/93270618-e43bee80-f787-11ea-86b1-b6aeac1d1402.png)

Thanks!

**Comment by Jrschellenberg** [comment]
@DaxBourcier I have updated this and it should be reflected on the cfms website in ~ 5 minutes.

Haha no worries! The main reason I would suggest to keep it is, it allows end users to quickly swap out map layers without having to reapply every single time. For example, if I wanted to quickly view specialty demand, or physician density amongst different queries!
