### ISSUE TITLE
Text for Link to HHR Platform

### ISSUE THREAD

**Issue by Jrschellenberg** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#74]
@DaxBourcier @st4nya 

Can you please just let me know what you would like the Text to say for the link to the HHR Platform under the Resources section.

To clarify this is what I am referring to 

![Screenshot from 2020-09-13 16-52-47](https://user-images.githubusercontent.com/6064137/93029603-c16fd580-f5e1-11ea-8d8d-56599790c402.png)

What would you like me to change the Text of

> Students Carms Interview Preparation
> Resource for familiarizing students with Interviews

To be?

Thank you and talk soon!

**Comment by Jrschellenberg** [comment]
Similarly, I will need Text for this as well!

![Screenshot from 2020-09-13 16-57-51](https://user-images.githubusercontent.com/6064137/93029671-5377de00-f5e2-11ea-938c-fd3749c7c9f2.png)

**Comment by ghost** [comment]
**Health Human Resources Platform**
Specialty planning tool
An interactive platform to guide medical students on specialty selection based on both personal interest and social accountability.


@DaxBourcier would be helpful to know your thoughts as well!

**Comment by DaxBourcier** [comment]
^ that is perfect!

**Comment by Jrschellenberg** [comment]
Thanks Misty!

It will look like this, If this is acceptable, you may close this ticket!

Screenshot 1:
![Screenshot from 2020-09-13 17-37-14](https://user-images.githubusercontent.com/6064137/93030332-d3ed0d80-f5e7-11ea-8f02-dbe2cacbe8ed.png)



Screenshot 2 :
![Screenshot from 2020-09-13 17-36-55](https://user-images.githubusercontent.com/6064137/93030336-d8192b00-f5e7-11ea-8653-3fddd7a726aa.png)
