### ISSUE TITLE
Other resources two columns

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#75]
Hey Justin,

If this is a quick fix, could we make the other resources tab into one column, because currently it looks like both titles are one line:

![image](https://user-images.githubusercontent.com/62123024/93030578-74e4c400-f5fa-11ea-9377-39e6a0fc30ec.png)

Alternatively, we could just and a line break earlier in the sentence on the top left so that the ":" are on the second line.

Thanks!

**Comment by Jrschellenberg** [comment]
@DaxBourcier I updated it to space the 2 columns out more, they will now take up 40% of the room each, leaving 20% of space between them to distinguish.

**Comment by DaxBourcier** [comment]
Hey Justin,

I don't think this worked when moving to the CFMS website:

![image](https://user-images.githubusercontent.com/62123024/93157897-82c14480-f6e1-11ea-986d-1b09a9959d19.png)

Also if possible to add a period at the end of the sentence after user guide. 

Thank you!

**Comment by Jrschellenberg** [comment]
@DaxBourcier Sorry I fixed this and then a regression occurred! It is fixed now!
