### ISSUE TITLE
Provincial Resources - Map View

### ISSUE THREAD

**Issue by BrandoCC** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#76]
When looking at the Map View, all the provincial resources appear for every health region, not one set for each province. Thus, there are several repeats for the resources.

**Comment by Jrschellenberg** [comment]
Hey Brandon, can you clarify exactly what you mean? Sorry but if I am understanding you correctly. This is working as expected.

When you are in the Map view, you are querying for all regions under the hood. This is why all of the Provincial Resources are showing.

**Comment by BrandoCC** [comment]
Hey Justin,    Sorry I know I wasn’t very specific. For example, NL has all their districts shown in under the provincial resources, thus NL has NL, Western, Central, Eastern, Labrador with all the same resources being shown. Thus, there is 5 reapeats for NL. This is true for all of the provinces. It has to do with how I inputed them into the excel sheet for the province. As I put them in under every speciality, thus it could be my fault haha. Hopefully you understand what I am saying.   Thanks,Brandon Collins From: Justin SchellenbergSent: September 13, 2020 9:58 PMTo: canadian-federation-of-medical-students/CFMS-Issue-TrackerCc: BrandoCC; AuthorSubject: Re: [canadian-federation-of-medical-students/CFMS-Issue-Tracker] Provincial Resources - Map View (#76) Hey Brandon, can you clarify exactly what you mean? Sorry but if I am understanding you correctly. This is working as expected.When you are in the Map view, you are querying for all regions under the hood. This is why all of the Provincial Resources are showing.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jrschellenberg** [comment]
Hey Brandon!

In order to fix this, we would need to fix the Data within the Province Resource template. What we can do is when the template is updated. I can re-upload it to the Database, it will then overwrite the previous entries and should fix the issue.

Let me know what you think! This may be something we have to shelve until after the launch. But if we can get it before I can upload it!

**Comment by BrandoCC** [comment]
I can do that no problem! I just need to know what I need to do lol. Should I just put them into the all section for each province? Brandon From: Justin SchellenbergSent: September 13, 2020 10:06 PMTo: canadian-federation-of-medical-students/CFMS-Issue-TrackerCc: BrandoCC; AuthorSubject: Re: [canadian-federation-of-medical-students/CFMS-Issue-Tracker] Provincial Resources - Map View (#76) Hey Brandon!In order to fix this, we would need to fix the Data within the Province Resource template. What we can do is when the template is updated. I can re-upload it to the Database, it will then overwrite the previous entries and should fix the issue.Let me know what you think! This may be something we have to shelve until after the launch. But if we can get it before I can upload it!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jrschellenberg** [comment]
Are you available tonight or either tomorrow night to maybe do a 15-minute call? Might be easier to explain over call. We may be able to do something in code too, but be easier if I get a better understanding of the issue!

**Comment by BrandoCC** [comment]
If you can call me now that would work best! 687-4139, if not tomorrow I am available after 1pm NL time!

Thanks
Brandon Collins

**Comment by Jrschellenberg** [comment]
@BrandoCC This is now fixed, It should be available for viewing in 5-10 minutes on the cfms website!

![Screenshot from 2020-09-13 20-14-10](https://user-images.githubusercontent.com/6064137/93033904-ca6ea000-f5fd-11ea-8023-75ce69a2e3c7.png)
