### ISSUE TITLE
Provincial Resources - Comparing jurisdictions 

### ISSUE THREAD

**Issue by BrandoCC** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#77]
When comparing jurisdictions WITHIN the same province the same provincial resources are duplicated.

**Comment by Jrschellenberg** [comment]
Hey Brandon, do you mind attaching a screenshot to explain this better? Please provide screenshots for all issues please!

**Comment by BrandoCC** [comment]
Sorry! I thought I attached the pictures. Here they are. This is comparing the NB districts zone 1 and 2, Provincial resources are repeated.   Brandon Collins From: Justin SchellenbergSent: September 13, 2020 9:59 PMTo: canadian-federation-of-medical-students/CFMS-Issue-TrackerCc: BrandoCC; AuthorSubject: Re: [canadian-federation-of-medical-students/CFMS-Issue-Tracker] Provincial Resources - Comparing jurisdictions (#77) Hey Brandon, do you mind attaching a screenshot to explain this better? Please provide screenshots for all issues please!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jrschellenberg** [comment]
This is related to #76

**Comment by Jrschellenberg** [comment]
@BrandoCC This is now fixed, It should be available for viewing in 5-10 minutes on the cfms website!
