### ISSUE TITLE
Bottom bar pull-up feature

### ISSUE THREAD

**Issue by ghost** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#78]
As per the screen recording I sent to Justin - the bottom par for the PD responses/specialty resources/etc can be pulled up beyond the screen, after which it can't be pulled back down. Once this happens, you have to refresh the page and re-input the data selection criteria. Would be very helpful if the bar couldn't be pulled up beyond the screen!

**Comment by Jrschellenberg** [comment]
Hey Misty! I actually noticed this too when I was QAing it.

I will investigate it, but if it is a fair amount of work, this may be postponed until after AGM!

**Comment by Jrschellenberg** [comment]
@st4nya This is now fixed, it was a fairly small fix!

**Comment by Jrschellenberg** [comment]
The Bar will now only be able to scroll as much as the Table, Map, And Graph Main screens respectively
