### ISSUE TITLE
% pursuing fellowship

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#79]
The % pursuing fellowship does not appear:

![image](https://user-images.githubusercontent.com/62123024/93080988-e78a8980-f664-11ea-9738-3195656e6c72.png)

**Comment by Jrschellenberg** [comment]
Hey, there @DaxBourcier Sorry but can you clarify this? I see the Percentage of Residents pursuing fellowship there. It is showing up as 0 if it is 0. or "-" if no data exists. It is there in Grey.

Also, can you tell me what Dataset you queried for this?

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is working as expected, there is no information for General Pathology other than 0 entered and only 9 of the datasets have 0, the rest were left blank.
