### ISSUE TITLE
dash sizes

### ISSUE THREAD

**Issue by basumoni** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#80]
Hi Justin,

I'm just playing with the platform now
I noticed sometimes the dash sizes are inconsistent when there is no information for a given dataset
I have attached a screen shot here
![dash size](https://user-images.githubusercontent.com/63878446/93131661-6ce05f00-f6a2-11ea-8da4-bba29c42d417.jpg)

as you can see the number of fellow exits per year has a larger dash than for the other datasets

**Comment by Jrschellenberg** [comment]
@basumoni Sorry but I can't replicate it on my machine, here is what it looks like for me.

![Screenshot from 2020-09-14 20-52-56](https://user-images.githubusercontent.com/6064137/93155715-518a4980-f6cc-11ea-9725-6eb83ef5ce13.png)


Can you tell me:
1.) What Browser are you using
2.) What operating system

I am also wondering if you are using any Browser extensions?

**Comment by Jrschellenberg** [comment]
@basumoni  I was able to hunt this down! Found the dashes and have fixed it now! will be available on the next release!
