### ISSUE TITLE
Map view click to drag not always working

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#84]
This had happened to me multiple times now and I don't know what I do for it to happen, but when I'm on map view, sometimes I click on a box or zoom in and the when I try to move around by clicking and dragging, it selects the text that is on the map instead and doesn't let me move around anymore. 

![image](https://user-images.githubusercontent.com/62123024/93158507-9de08400-f6e2-11ea-92c3-f8cdf58f2cfa.png)

To fix it, I have to zoom way in and then it goes back to normal. I can zoom back out and it will work like normal again.

**Comment by Jrschellenberg** [comment]
@DaxBourcier I am having a hard time replicating this bug

can you tell me the following:

1.) What Operating System you are using
2.) What Browser you are using?
3.) Are you using a mouse or a Track pad?

Thanks and talk soon!

**Comment by DaxBourcier** [comment]
Hey Justin,

1) macOS Catalina
2) Chrome
3) Track pad (but occurred using mouse as well)

This never happened before on the quirky-edison link.

**Comment by DaxBourcier** [comment]
I was just able to reproduce it! Basically when you try and move the blue pins from the Canadian region view, the second time you move it it freezes and wont allow you to click and drag anymore.

**Comment by Jrschellenberg** [comment]
@DaxBourcier Try it again. There was a bug where it wasn't registering the CaRMS GeoJSON. I couldn't replicate the Map freezing though so test that and let me know!

If it seems to be working you can close this ticket!

**Comment by DaxBourcier** [comment]
Not able to replicate it again!
