### ISSUE TITLE
Last ratio doesn't work

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#86]
Hey Justin,

The last ratio doesn't work (ratio of vacancies to number of physicians). You select it and then it doesn't appear on the map when you apply. 

![image](https://user-images.githubusercontent.com/62123024/93207569-8977a800-f731-11ea-8fc4-2c9344a9601f.png)

**Comment by DaxBourcier** [comment]
Also for this specific ratio, I would need to confirm the following informations so that I can update the User Guide appropriately --> does this use averages for the denominator (since we do have two sources (CIHI and CMA) for this dataset)? If it does not, what is the source used for the denominator? I know that the nominator is only provided by CMA. 

Thanks!

**Comment by Jrschellenberg** [comment]
@DaxBourcier As we talked about previously on our call and you confirmed that it was ok. The Data ratios logic is as follows

If you are trying to calculate a Dataset from across 2 sources (more than 1 row in the excel template at a time) This is not possible, and cannot be done. 

If the Template import, has both the Datasets (exists and isn't '-' or null), it will calculate it provided:
- The denominator isn't 0 
- Both of the values exist

If another CSV template has the required information to calculate the data set it will as well.


Then when the Front end receives the Data, if it comes from more than 1 source, it will average that data and display it to the user as averaged data. Hope this helps!

**Comment by Jrschellenberg** [comment]
@DaxBourcier For this particular issue, can you tell me the steps to replicate? Sorry but it appears for your screenshot you just don't have it selected, I am able to select it. 

Are you trying to select it and it won't select? It seems like you don't have it selected right now.

I am using https://cfms.org/resources/health-human-resources-platform/map#


![Screenshot from 2020-09-15 10-16-02](https://user-images.githubusercontent.com/6064137/93229730-8635e980-f73c-11ea-815f-bccecccc661f.png)

**Comment by Jrschellenberg** [comment]
@DaxBourcier O I think I just replicated it. Can you confirm, this happens after you have already queried for data on the map?

**Comment by DaxBourcier** [comment]
1) Ok no problem, so is it both CMA data for this ratio? This is what I need to know.

2) Exactly, when I select it then click apply, it just doesn't show up in the legend or on the map, then when I click the data sets again its like I never selected it.

Cheers

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is now fixed! It was quite the bug haha, but got it squashed!

If you find any other issues, just reopen the ticket!

**Comment by DaxBourcier** [comment]
Eliminate the bugs!! Justin I think this is pretty much it! The HHRTF have until tonight to review and post up Github issues and I plan on sharing with the Board the completed HHR platform and presentation for Sunday tonight as well! Have a nice day!
