### ISSUE TITLE
CAPER data mistake

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#87]
I made a mistake here, I'm really sorry. It should be a quick fix. 

Remember a while ago, I had asked to change the name of one of the CAPER data sets.. I was completely wrong. In fact, the way it is called in the template is actually correct! so I think we can just remove the code that made it change the name of this data set apply to the front end. Here's more details:
  - Name in template " Number of graduates 2 years ago"
  - I asked for it to be changed to "Number of 2 year post graduates working in same province" (this is because for some reason I didn't see the other data set that shows just this...)
  - If it could be changed back to how it was originally that would be perfect.

The ratio that includes both these data sets is actually written correctly and it probably working properly because the outputs are decimals. (if it they were both the same data sets it would equal to 1 everywhere).

![image](https://user-images.githubusercontent.com/62123024/93221534-45da6980-f744-11ea-96d3-2e8f04a2a272.png)

Thanks!

**Comment by Jrschellenberg** [comment]
@DaxBourcier To clarify, you want me to change the Dataset back to its original name `Number of graduates from province 2 years ago` Correct?

**Comment by DaxBourcier** [comment]
Yes please. Sorry about the inconvenience.

**Comment by DaxBourcier** [comment]
Also we just need to make sure that it's the right data set that appears under each. In other words, just making sure we didn't flip flop those data sets by changing their names.

**Comment by Jrschellenberg** [comment]
@DaxBourcier I have removed the Dataset rename, it now says:

`Number of graduates from province 2 years ago`

To answer your question, we will be ok! I tested it with some data. I also have been structuring edge cases to not conflict too much with the Codebase, so we should be fine!

Closing ticket but if you need any additional information, just let me know and open it back up!
