### ISSUE TITLE
User Guide Update

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#88]
I changed the User Guide to add the ratios and calculated data sets. Also added the layer information etc.

If possible to re-upload the User Guide.

I only need two things before I can send you the final draft:
1. Issue with the # of vacancies to number of physicians (if both CMA data sets that are used or if denominator is CIHI)
2. I need to take a screenshot of the map view with the Physician Density layer.

Will upload the link here as soon as possible.

**Comment by Jrschellenberg** [comment]
@DaxBourcier Just going to add some clarity around Number 1. The short Answer is only CMA has this Ratio Calculated, CIHI does not. It is missing # of Vacancies


Let me try to clarify:
When a Template is uploaded, a short summary of the relevant steps would be.
- A row in the Excel sheet gets uploaded.
- Looks at all the Dataset columns and picks out columns required for calculating data ratios.
   For Each Data Ratio Calculation, it will be calculated if
     - If the Datasets in that row has the two columns required for the Dataset
     - Neither of those two Datasets are `null` or `-`
     - The Demoninator Column is not 0 (can't divide by 0)

Here is the raw code
```
if(array_key_exists('Number of vacancies', $data) && array_key_exists('Number of physicians', $data)){
            // Ratio of Number of vacancies to Number of physicians
            if($this->notEmpty($data['Number of vacancies'], true) && $this->notEmpty($data['Number of physicians']))
            {
                $data['Ratio of Number of vacancies to Number of physicians'] = strval(intval($data['Number of vacancies']) / intval($data['Number of physicians']) );
            }
        }
```

notEmpty is this function here:
```
private function notEmpty($value, $allowZeroValue = false){
        $val = trim($value); // remove whitespace on both sides

        if($allowZeroValue && ($val === "0" || $val === "0.0" || $val === 0)){
            return true;
        }

        if (strtolower($val) == "null" or strtolower($val) == "-"){
            $val = null;
        }

        return !empty($val);
    }
```


If there is a row (1 entry of data with all the columns) in the excel that contains the Columns of

`'Ratio of Number of vacancies to Number of physicians`
and
`Number of vacancies`

Then the ratio will be generated, provided they contain a value not `null` or `-` and the `Number of Vacancies` does not = `0`

For this particular example, it appears only CMA was able to calculate the Ratio. CIHI is missing one of the requirements 
- `Number of Vacancies`

If CIHI had both Columns of data (The Datasets), per row (each entry), in their CSV import (The Excel file), then a Data ratio would be calculated for CIHI as well!

Hope this helps! Let me know if you have any other questions!

I will update this ticket when I update the wording for the Map view!

**Comment by Jrschellenberg** [comment]
@DaxBourcier The text should be updated shortly, Closing ticket for now, but if you have another question just open it back up!

**Comment by Jrschellenberg** [comment]
Actually I just realized you will provide the link here, leaving it open my apologies!

**Comment by DaxBourcier** [comment]
Here it is:

https://drive.google.com/file/d/1Z2FdshYgFJOrHbnCkm1vzWGbI_QSRiaU/view?usp=sharing

Thanks Justin!

**Comment by Jrschellenberg** [comment]
@DaxBourcier This is now added to the new website. Closing ticket, if any other issues just reopen it!
