### ISSUE TITLE
LASIK MD discount card is not appearing when printing the page

### ISSUE THREAD

**Issue by davidjbrandon** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#90]
Attempted to print LASIK MD discount card in Firefox, Chrome, and Safari with no success, just prints a blank page with header url and timestamp. 

Was able to get a copy printed by removing `body *` selector from the print.css `@media` rule. 

[Here is the url](https://www.cfms.org/resources/lasik-membership-card).

**Comment by Jrschellenberg** [comment]
Thank you for bringing this up! You were right on the money, the whole body was being displayed none via css

- It is now fixed!
