### ISSUE TITLE
Security issue in nonce generation

### ISSUE THREAD

**Issue by MarcelloTheArcane** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#91]
Hello!

I made `netlify-plugin-csp-generator`, which you've cloned [here](https://github.com/canadian-federation-of-medical-students/netlify-plugin-csp-generator).

I noticed that is has an insecure function for generating nonces:
```js
// functions.js

function insertNonce (dom) {
  return selector => {
    for (const matchedElement of dom.window.document.querySelectorAll(selector)) {
      let att = dom.window.document.createAttribute('nonce');
      att.value = '41SWRENqnTUAb6n3';
      matchedElement.setAttributeNode(att);
    }
  }
}
```
[Source](https://github.com/canadian-federation-of-medical-students/netlify-plugin-csp-generator/blob/e5452aa78e7dc46698f6ae3852c1ef42eb8a1f9a/functions.js#L97-L105)

## The flaw is this: 

> A nonce is a randomly generated value that is not intended to be reused.
> [Source](https://engineering.gusto.com/nonce-based-content-security-policy-csp-in-rails/#:~:text=A%20nonce%20is%20a%20randomly%20generated%20value%20that,HTML%20attribute%20to%20all%20script%20and%20style%20tags.)

The point of a nonce is that it allows the browser to recognised code that you have authorised, but that isn't known (which would be handled by a checksum instead).  It must be a cryptographically-secure randomly-generated base64 string, and must be unique for at least each session (ideally every nonce used in the page would be unique).  This is because a hacker can read a hard-coded nonce, and inject code **with the same nonce**, which would be validated by the browser.

Since the nonce here is a hardcoded string, it means that the nonce is ineffective, and is a security flaw.

**Comment by Jrschellenberg** [comment]
Hey there Marcello! I appreciate you taking the time to reach out and post this for us! It is much appreciated.

Although we are using a hardcoded string here. This string is being intercepted and rewritten to a true nonce every time the page loads. If you open up the CFMS source and refresh the page, you will see that there is a changing nonce is being updated upon every page refresh.

Also, I just wanted to say thank you for putting together this awesome Library that we were able to use as well!

**Comment by MarcelloTheArcane** [comment]
Thanks for confirming, just wanted to make sure you were aware!

No problem 🙂
